### ISSUE TITLE
socket.error: [Errno 97] Address family not supported by protocol

### ISSUE THREAD

**Issue by supermamie** [liftoff/GateOne#242]
I just installed Gate One on my raspberry pi on debian (uname -a = Linux raspberrypi 3.2.27+ #250 PREEMPT Thu Oct 18 19:03:02 BST 2012 armv6l GNU/Linux)
My FAI enable IPV6 (seems that this error can be linked to that)

When I try to start gate on (./gateon.py) I get this error : 

Traceback (most recent call last):
  File "./gateone.py", line 3480, in <module>
    main()
  File "./gateone.py", line 3429, in main
    https_server.listen(port=go_settings['port'], address=addr)
  File "/usr/local/lib/python2.7/dist-packages/tornado/tcpserver.py", line 113, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 85, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 224, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 99] Cannot assign requested address

**Comment by snehaldpatel1992** [comment]
I am starting Air Notifier service  on Ubuntu and I am getting error like this...

socket.error: [Errno 97] Address family not supported by protocol
[I 150525 13:27:02 airnotifier:167] Starting AirNotifier server
Traceback (most recent call last):
  File "airnotifier.py", line 253, in <module>
    AirNotifierApp(services=services).main()
  File "airnotifier.py", line 169, in main
    http_server.listen(options.port)
  File "/usr/local/lib/python2.7/dist-packages/tornado/tcpserver.py", line 113, in listen
    sockets = bind_sockets(port, address=address)
  File "/usr/local/lib/python2.7/dist-packages/tornado/netutil.py", line 69, in bind_sockets
    sock = socket.socket(af, socktype, proto)
  File "/usr/lib/python2.7/socket.py", line 187, in __init__
    _sock = _realsocket(family, type, proto)
