### ISSUE TITLE
uncaught exception in write_errr: 'ascii' code can't decode byte 0xe2 in position 1484, ordinal not in range. 

### ISSUE THREAD

**Issue by kevstev** [liftoff/GateOne#249]
So I am using python 2.7, and tornado 3.0, on an arm platform with the latest from git. When I try to access gateone through the url, after accepting certificates, it comes up, but then the terminal window just has undefined scrolling down throughout it, then it closes terminals and starts again in a loop. 

Here is the trace on the console: 

[I 130507 22:03:34 termio:1506] Finalizing the log for pid 20370 (this can take
some time).
[I 130507 22:03:34 gateone:1160] WebSocket closed (ANONYMOUS 192.168.1.4).
[I 130507 22:03:47 app_terminal:379] Active Terminal Plugins: bookmarks, conven
ence, example, html, logging, logging_plugin, mobile, notice, playback, ssh
[I 130507 22:03:48 gateone:1072] WebSocket opened (ANONYMOUS 192.168.1.4) via o
igin diskstation.
[I 130507 22:03:50 gateone:1449] User ANONYMOUS authenticated successfully via
rigin diskstation (location: default).
[E 130507 22:03:52 gateone:1143] Error/Unknown WebSocket action, terminal:bookm
rks_get: u'terminal:bookmarks_get' (gateone.py line 1136)
[E 130507 22:03:56 web:778] Uncaught exception in write_error
    Traceback (most recent call last):
      File "/opt/local/lib/python2.7/site-packages/tornado/web.py", line 776, i
 send_error
        self.write_error(status_code, *_kwargs)
      File "/opt/local/lib/python2.7/site-packages/tornado/web.py", line 809, i
 write_error
        self.finish(self.get_error_html(status_code, *_kwargs))
      File "gateone.py", line 2337, in get_error_html
        data = f.read()
      File "/opt/lib/python2.7/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1484:
rdinal not in range(128)
[W 130507 22:03:56 web:1514] 404 GET /static/ubuntumono-normal.woff (192.168.1.
) 259.54ms
[E 130507 22:04:02 gateone:1143] Error/Unknown WebSocket action, terminal:ssh_g
t_identities: u'terminal:ssh_get_identities' (gateone.py line 1136)
[I 130507 22:04:14 gateone:1160] WebSocket closed (ANONYMOUS 192.168.1.4).

I don't see any additional logs, and changing the config to debug=true didn't seem to add any additional output- there are also no logs. 

This appears to be at least somewhat related to ssh, so I will include my 50terminal.conf as well: 

```
"*": {
    "terminal": { // These settings apply to the "terminal" application
        "commands": {"SSH": "/opt/gateone/applications/terminal/plugins/ssh/
```

scripts/ssh_connect.py -S '%SESSION_DIR%/%SESSION%/%SHORT_SOCKET%' --sshfp -a '-
oUserKnownHostsFile=\\"%USERDIR%/%USER%/.ssh/known_hosts\\"'"},
            "default_command": "SSH",
            "dtach": true,
            "session_logging": true,
            "session_logs_max_age": "30d",
            "syslog_session_logging": false
        }
    }
}

Not really sure what is going on here, I have a feeling this may be config related, but I am not sure...

**Comment by patsissons** [comment]
i tracked down the mysterious _c: applet not found_ message. That comes from `busybox`, which will happen if you symlink `/bin/sh` to `busybox` (as you would expect on ultra light systems). In my case, this is happening on my NAS.

the `c` in this case refers to the _applet_ that was requested, i.e. `busybox c`

I'm still not sure what is causing a `c` to get executed though...
