### ISSUE TITLE
Impossible to run in userland with virtualenv

### ISSUE THREAD

**Issue by denouche** [liftoff/GateOne#431]
Hi

I just installed GateOne as recommanded using:

`$ python setup.py install`

Now I try to run it, but the message I get is the following:

$ gateone
[W 140528 09:24:34 app_terminal:2711] dtach command not found.  dtach support has been disabled.
[I 140528 09:24:34 server:4026] Imported applications: Terminal
[I 140528 09:24:34 server:4168] Version: 1.2.0 (20140516085214)
[I 140528 09:24:34 server:4169] Tornado version 3.2
[I 140528 09:24:34 server:4189] Connections to this server will be allowed from the following origins: 'localhost:10443 127.0.0.1:10443 hostname:10443'
[E 140528 09:24:34 utils:621] Could not create directory: /etc/gateone/ssl
Traceback (most recent call last):
  File "/home/user/virtualEnvironment/devEnv/bin/gateone", line 9, in <module>
    load_entry_point('gateone==1.2.0', 'console_scripts', 'gateone')()
  File "/home/user/virtualEnvironment/devEnv/local/lib/python2.7/site-packages/gateone-1.2.0-py2.7.egg/gateone/core/server.py", line 4201, in main
    mkdir_p(ssl_base)
  File "/home/user/virtualEnvironment/devEnv/local/lib/python2.7/site-packages/gateone-1.2.0-py2.7.egg/gateone/core/utils.py", line 616, in mkdir_p
    os.makedirs(path)
  File "/home/user/virtualEnvironment/devEnv/lib/python2.7/os.py", line 150, in makedirs
    makedirs(head, mode)
  File "/home/user/virtualEnvironment/devEnv/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/etc/gateone'

Is there any way to custom the /etc/gateone directory, in order to be able to run gateone in userland ?
Thank you

**Comment by smartass101** [comment]
I have the same problem running in a fresh virtualenv with master branch.
```bash
$ gateone --version
Gate One:
        Version: 1.2.0 (20150624125036)
Installed Applications:
        Terminal Version: 1.2
```
On first run it created `$HOME/.gateone/`, but now when I run it does not respect `--settings-dir`
```
$ gateone
[W 151009 15:11:41 app_terminal:2805] dtach command not found.  dtach support has been disabled.
[I 151009 15:11:41 server:4180] Gate One License: AGPLv3 (http://www.gnu.org/licenses/agpl-3.0.html)
[I 151009 15:11:41 server:4189] Imported applications: Terminal
[I 151009 15:11:41 server:4341] Version: 1.2.0 (20150624125036)
[I 151009 15:11:41 server:4342] Tornado version 4.2.1
[I 151009 15:11:41 server:4362] Connections to this server will be allowed from the following origins: 'localhost:10443 127.0.0.1:10443 distributor.fjfi.cvut.cz:10443 distributor:10443 127.0.1.1:10443'
[E 151009 15:11:41 utils:622] Could not create directory: /etc/gateone/ssl
[E 151009 15:11:41 server:4378] Gate One could not create {ssl_base} ({e}). Are you using the correct --settings_dir?
``` 

I think the problem is that according to `--help` output `--settings_dir` defaults to `$HOME/.gateone/conf.d` as it should, but the SSL options do not respect the setting
```
$ gateone -h 2>&1 | grep -B 2 /etc 
  --certificate                    Path to the SSL certificate.  Will be auto-
                                   generated if not found. (default
                                   /etc/gateone/ssl/certificate.pem)
--
  --keyfile                        Path to the SSL keyfile.  Will be auto-
                                   generated if none is provided. (default
                                   /etc/gateone/ssl/keyfile.pem)
--
  --certificate                    Path to the SSL certificate.  Will be auto-
                                   generated if not found. (default
                                   /etc/gateone/ssl/certificate.pem)
--
  --keyfile                        Path to the SSL keyfile.  Will be auto-
                                   generated if none is provided. (default
                                   /etc/gateone/ssl/keyfile.pem)
```
These settings are also wrongly set in `$HOME/.gateone/conf.d/10server.conf` after they are generated
```
$ grep /etc ~/.gateone/conf.d/10server.conf 
            "certificate": "/etc/gateone/ssl/certificate.pem",
            "keyfile": "/etc/gateone/ssl/keyfile.pem",
```

I fixed this by
```
sed -i "s@/etc/gateone@${HOME}/.gateone@g" ~/.gateone/conf.d/10server.conf
```
and now it works.

**Comment by bubbapizza** [comment]
You're right, that's a bug.  I had the same problem and the fix worked!
