### ISSUE TITLE
python setup.py --command-packages=stdeb.command bdist_deb is broken

### ISSUE THREAD

**Issue by mfonville** [liftoff/GateOne#460]
I get the following error with the latest git version when trying to build a deb package:

```
 dpkg-source -b gateone-1.2.0
dpkg-source: info: using options from gateone-1.2.0/debian/source/options: --extend-diff-ignore=\.egg-info$
dpkg-source: info: using source format `3.0 (quilt)'
dpkg-source: info: building gateone using existing ./gateone_1.2.0.orig.tar.gz
dpkg-source: warning: executable mode 0775 of 'build/gateone' will not be represented in diff
dpkg-source: info: local changes detected, the modified files are:
 gateone-1.2.0/build/gateone
 gateone-1.2.0/build/gateone.conf
dpkg-source: info: you can integrate the local changes with dpkg-source --commit
dpkg-source: error: aborting due to unexpected upstream changes, see /tmp/gateone_1.2.0-1.diff.A0xPy0
dpkg-buildpackage: error: dpkg-source -b gateone-1.2.0 gave error exit status 2
Traceback (most recent call last):
  File "setup.py", line 288, in <module>
    **extra
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/stdeb/command/bdist_deb.py", line 22, in run
    self.run_command('sdist_dsc')
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python2.7/dist-packages/stdeb/command/sdist_dsc.py", line 141, in run
    remove_expanded_source_dir=self.remove_expanded_source_dir,
  File "/usr/local/lib/python2.7/dist-packages/stdeb/util.py", line 1341, in build_dsc
    dpkg_genchanges(cwd=fullpath_repackaged_dirname)
  File "/usr/local/lib/python2.7/dist-packages/stdeb/util.py", line 514, in dpkg_genchanges
    process_command(args,cwd=cwd)
  File "/usr/local/lib/python2.7/dist-packages/stdeb/util.py", line 169, in process_command
    check_call(args, cwd=cwd)
  File "/usr/local/lib/python2.7/dist-packages/stdeb/util.py", line 45, in check_call
    raise CalledProcessError(retcode)
stdeb.util.CalledProcessError: 2
```

**Comment by flynet70** [comment]
Debian 7.8 64
Also broken

**Comment by Drakonas** [comment]
Can someone please take a look at what is wrong with this? Is it GateOne's fault? Or is it the horrible Python 3 integration in Ubuntu 14.04?

**Comment by fsimon21** [comment]
hello,
i have the same problem on Ubuntu 14.04 and the last master source, there is no news about this problem ?

thanks

**Comment by raven7** [comment]
i have the same problem  tooo.any suggustion?! please I need It....

**Comment by smartass101** [comment]
The whole problem seems to be the init handling. Setting `skip_init = True` makes this problem go away, but then I have to make my own init file.

**Comment by bubthegreat** [comment]
@smartass101 - For those of us getting here via google 3 years later - if you're still around, where is the init file made?
