### ISSUE TITLE
Uncaught exception in /ws

### ISSUE THREAD

**Issue by DonRichie** [liftoff/GateOne#466]
Hi,
i updated my gateone instance by using
git pull
service gateone stop
python setup.py install
service gateone start

The server starts but when a client wants to connect the server says:

[E 140924 01:51:26 websocket:325] Uncaught exception in /ws
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado-3.2-py2.7-linux-x86_64.egg/tornado/websocket.py", line 322, in wrapper
        return callback(_args, *_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/core/server.py", line 1595, in open
        logging.debug("open() origin: %s" % self.origin)
    AttributeError: 'ApplicationWebSocket' object has no attribute 'origin'

What could make this happen and how to fix that?

**Comment by DonRichie** [comment]
I tested using gateone today with a fresh install.
The same error Message occured when the browser says "attemting to connect to server"
