### ISSUE TITLE
Unable to install gateone on windows

### ISSUE THREAD

**Issue by ravinsharma7** [liftoff/GateOne#503]
Hi,

I cloned the gateone repo from github to my window machine, and tried to install it. I can't get pass this error.

Traceback (most recent call back):
  File "./setup.py", line 212, in (module)
    if os.getuid() == 0 and not skip_init:
AttributeError: 'module object has no attribute 'getuid'

I have python 3.4.3 installed and tornado 2.2 installed

**Comment by DJD-Code-Studio** [comment]
I too have the same issue with Python 2.7.2.
I even have a linux like environment created with msys installed under mingw32.


$ python setup.py install --prefix=/home/duttad/GateOne/
Traceback (most recent call last):
  File "setup.py", line 211, in <module>
    if os.getuid() == 0 and not skip_init:
AttributeError: 'module' object has no attribute 'getuid'




@ravinsharma7 Did you get any help from google so far on this ? If yes, then can you please share ?

**Comment by gmkbenjamin** [comment]
getuid() seems to be a Linux/Unix only thing. Will Docker work?
