### ISSUE TITLE
No Display - Not Prompts

### ISSUE THREAD

**Issue by cjmellor** [liftoff/GateOne#507]
Hi,

I've tried to install this on a Homestead and a DigitalOcean VPS, and I've got the same error each time, so I'm wondering if it's an issue with the script.

I have got an error:

```
[E 150312 17:41:02 http1connection:700] Uncaught exception
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 691, in _server_request_loop
        ret = yield conn.read_response(request_delegate)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 807, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 810, in run
        yielded = self.gen.throw(*sys.exc_info())
      File "/usr/local/lib/python2.7/dist-packages/tornado/http1connection.py", line 166, in _read_message
        quiet_exceptions=iostream.StreamClosedError)
      File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 807, in run
        value = future.result()
      File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 209, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
    SSLError: [Errno 8] _ssl.c:510: EOF occurred in violation of protocol
```

Does this tell you much? I don't know the first thing about Python...

Many thanks.

**Comment by liftoff** [comment]
Are you using the latest version of Gate One and the latest version of Tornado?  Also, make sure your SSL certificates got generated correctly.  Remove the two .pem files in your /etc/gateone/ssl directory to force them to be re-generated.

You can force tornado to upgrade to the latest version like so:

    sudo pip install --upgrade tornado

Let me know what version of Gate One you're using (the commit number) too.
