### ISSUE TITLE
Terminal starts then immediately crashes

### ISSUE THREAD

**Issue by musicmunky** [liftoff/GateOne#514]
I can bring up the initial GateOne window, but as soon as I attempt to go further (click the "Terminal:SSH" icon) it crashes back to that page.  It's failing with the following error:

```
Traceback (most recent call last):
    File "/home/tandrews/GateOne/gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py", line 23 in <module>
        from concurrent import futures
ImportError:  No module named concurrent
```

I've verified that the futures module is installed - any thoughts on this one would be appreciated.
Thanks!

**Comment by musicmunky** [comment]
So I went through the entire install process again from scratch - basically loaded a fresh image of the VM and started over again, and I'm still getting that error:

```
Traceback (most recent call last):
    File "/usr/local/lib/python2.7/site-packages/gateone-1.2.0-py2.7.egg/gateone/applications/terminal/plugins/ssh/scripts/ssh_connect.py", line 23 in <module>
        from concurrent import futures
ImportError:  No module named concurrent
```

Any ideas on this one?

**Comment by fffy2366** [comment]
I I encountered the same problem.
