### ISSUE TITLE
gateone.error

### ISSUE THREAD

**Issue by krishnasripada** [liftoff/GateOne#527]
Hi,

I've been working on Gateone terminal for the past few weeks and I'm getting an error while embedding Gateone into another application:

[E 150423 13:23:32 server:1737] {"ip_address": "127.0.0.1"} Error in WebSocket action, go:authenticate: Expected bytes, unicode, or None; got <type 'dict'> (/usr/local/lib/python2.7/dist-packages/tornado/escape.py line 203)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/core/server.py", line 1730, in on_message
    self.actions[key](value)
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/core/server.py", line 2099, in authenticate
    value=settings['auth'], max_age_days=expiration)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 613, in get_secure_cookie
    min_version=min_version)
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 2944, in decode_signed_value
    value = utf8(value)
  File "/usr/local/lib/python2.7/dist-packages/tornado/escape.py", line 203, in utf8
    "Expected bytes, unicode, or None; got %r" % type(value)
TypeError: Expected bytes, unicode, or None; got type 'dict'

What could be the reason for this error?

**Comment by krishnasripada** [comment]
I solved it. It was a tornado issue and not gateone
