### ISSUE TITLE
Terminal sharing template not found

### ISSUE THREAD

**Issue by flashvoid** [liftoff/GateOne#532]
I wonder why no one reported it yet. 
Starting from 0ea8ad167d2ec79a68dfb1916cb7f6e76cdce265 terminal sharing fails trying to find `templates/index.html` when template is really called `templates/share.html`. 

I'm happy to submit pull request but should i just rename a file or fix `class SharedTermHandler(BaseHandler)` instead ?

```bash
[E 150508 23:36:27 web:1421] Uncaught exception GET /terminal/shared/bla (111.69.229.101)
    HTTPServerRequest(protocol='https', host='blix-vpn.ddau.biz', method='GET', uri='/terminal/shared/bla', version='HTTP/1.1', remote_ip='111.69.229.101', headers={'Connection': 'keep-alive', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate', 'Cookie': '_ga=GA1.2.189817604.1426476548; gateone_user="2|1:0|10:1430712791|12:gateone_user|108:eyJ1cG4iOiAiQU5PTllNT1VTIiwgInNlc3Npb24iOiAiWm1Fek16RTRNalpqWVRKak5ETmxNbUkyTkRWaU1EQmlZVEl3WkRNMFpXUXhaIn0=|5614649d449c624d8ce75ca79a69083b57c043d31f1cd2088d007422134516c0"; __utma=64466684.189817604.1426476548.1430712797.1430975623.2; __utmz=64466684.1430712797.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)', 'Host': 'blix-vpn.ddau.biz', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:37.0) Gecko/20100101 Firefox/37.0'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 1346, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/applications/terminal/app_terminal.py", line 159, in get
        prefs=prefs
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 664, in render
        html = self.render_string(template_name, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 768, in render_string
        t = loader.load(template_name)
      File "/usr/local/lib/python2.7/dist-packages/tornado/template.py", line 343, in load
        self.templates[name] = self._create_template(name)
      File "/usr/local/lib/python2.7/dist-packages/tornado/template.py", line 370, in _create_template
        with open(path, "rb") as f:
    IOError: [Errno 2] No such file or directory: u'/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/applications/terminal/templates/index.html'
```

**Comment by GP03DHulaki** [comment]
I also met the same problem, and thanks for your advice, I've fixed it by renaming the file with `templates/index.html` temporarily.
