### ISSUE TITLE
Google OpenID 2 doesn't work anymore.

### ISSUE THREAD

**Issue by omata-metamax** [liftoff/GateOne#534]
Hello,

Recently Google deprecated OpenID 2 and is using a new OpenID Connect, Since that I can't login to my GO server anymore, There is any way to fix this?

BTW Was GO removed from PyPy index? because I installed it using pip but now it can find gateone in the index. My instaled version is 1.2.0

Best regards,

**Comment by Xat59** [comment]
Hi guys,

Personally I'm not able to use Google authentication (OAuth) with recent GateOne .

**Comment by omata-metamax** [comment]
OpenID 2 was dicontinued since Apr 20.

**Comment by omata-metamax** [comment]
I just did see that Google auth mechanism is handled by Tornado, I'm guessing that New Google auth metodology must be updated first on Tornado framework. :(

**Comment by omata-metamax** [comment]
Hi,

I asked for Google Connect implementation on tornado's github repo and they replied that they will not support soon Google Connect but instead Oauth2 can be used because Google still support it. I don't know If a change in the code is needed for this issue.

Regards,

**Comment by omata-metamax** [comment]
Nevermind,

I just comapred the code installed on my computer and the one available on the repo and mine is outdated, I will find the way to update it.

Thanks.

**Comment by omata-metamax** [comment]
Issue solved,

Installed by issuing:
``` bash
sudo pip install https://github.com/liftoff/GateOne/archive/master.zip
```

Then I reconfigured all again and done!

Regards,
Oscar

**Comment by omata-metamax** [comment]
@Xat59 My issue wasn't that, I was using an old version of GateOne without support for Oauth2, I just upgraded to latest and now I can use Oauth2 protocol. I just followed all directions from log file asking for user ID and user secret and all is set. You must create a Google Project first to generate these IDs.

Regards,
Oscar

**Comment by Xat59** [comment]
@omata-metamax I have a Google projet with ID and secret, but they don't work .

On the web interface I get "The authentication object was denied by the server. Click OK to reload the page."

In logs I get :
[E 150517 22:15:51 web:1407] Uncaught exception GET /auth?code=4/8YfqovmGzIZMK54-ksC0i6JuQZOD1sRdlf7P8ihl_Mc.IqO43CunwS8boiIBeO6P2m_6pBPHmgI (192.168.1.1)
    HTTPServerRequest(protocol='https', host='blabla.net:4443', method='GET', uri='/auth?code=4/8YfqovmGzIZMK54-ksC0i6JuQZOD1sRdlf7P8ihl_Mc.IqO43CunwS8boiIBeO6P2m_6pBPHmgI', version='HTTP/1.1', remote_ip='192.168.1.1', headers={'Accept-Language': 'en-US,en;q=0.8,fr;q=0.6', 'Accept-Encoding': 'gzip, deflate, sdch', 'Host': 'blabla.net:4443', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8', 'User-Agent': 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.152 Safari/537.36', 'Connection': 'keep-alive', 'Cookie': 'JSESSIONID=1w092kw7p4vfx; player-786174=5; __utma=216242207.1197496179.1429783887.1431521428.1431530793.8; __utmc=216242207; __utmz=216242207.1429783887.1.1.utmcsr=(direct)|utmccn=(direct)|utmcmd=(none)', 'Cache-Control': 'max-age=0', 'Allow-Chrome-Signin': '1'})
    Traceback (most recent call last):
      File "/usr/local/lib/python2.6/dist-packages/tornado-4.0.2-py2.6-linux-x86_64.egg/tornado/web.py", line 1334, in _execute
        result = yield result
      File "/usr/local/lib/python2.6/dist-packages/tornado-4.0.2-py2.6-linux-x86_64.egg/tornado/gen.py", line 628, in run
        value = future.result()
      File "/usr/local/lib/python2.6/dist-packages/tornado-4.0.2-py2.6-linux-x86_64.egg/tornado/concurrent.py", line 109, in result
        raise_exc_info(self._exc_info)
      File "/usr/local/lib/python2.6/dist-packages/tornado-4.0.2-py2.6-linux-x86_64.egg/tornado/gen.py", line 633, in run
        yielded = self.gen.send(value)
      File "/usr/local/lib/python2.6/dist-packages/gateone-1.2.0-py2.6.egg/gateone/auth/authentication.py", line 350, in get
        self._on_auth(user)
      File "/usr/local/lib/python2.6/dist-packages/gateone-1.2.0-py2.6.egg/gateone/auth/authentication.py", line 379, in _on_auth
        self.user_login(user)
      File "/usr/local/lib/python2.6/dist-packages/gateone-1.2.0-py2.6.egg/gateone/auth/authentication.py", line 159, in user_login
        user_dir = os.path.join(self.settings['user_dir'], upn)
    UnboundLocalError: local variable 'upn' referenced before assignment
[E 150517 22:15:51 web:1811] 500 GET /auth?code=4/8YfqovmGzIZMK54-ksC0i6JuQZOD1sRdlf7P8ihl_Mc.IqO43CunwS8boiIBeO6P2m_6pBPHmgI (192.168.1.1) 837.92ms

**Comment by omata-metamax** [comment]
Can you post your configuration file 50terminal.conf?
