### ISSUE TITLE
AssertionError: version mismatch, 0.8.6 != 1.5.2

### ISSUE THREAD

**Issue by bl4ckc00k1e** [liftoff/GateOne#599]
Hi all, how can i fix this?? with out SSL all works fine... but i need work on SSL...

I try to install all in /opt but my instalations fails too, aniway, this is the output of the execution

XXXXXX:/etc/gateone# gateone
[I 160420 12:16:27 server:4179] Gate One License: AGPLv3 (http://www.gnu.org/licenses/agpl-3.0.html)
[I 160420 12:16:27 server:4188] Imported applications: Terminal
[I 160420 12:16:27 server:4340] Version: 1.2.0 (20151116212858)
[I 160420 12:16:27 server:4341] Tornado version 4.3
[I 160420 12:16:27 server:4361] Connections to this server will be allowed from the following origins: 'localhost 127.0.0.1 RosaliaFruity 10.0.0.1 192.168.1.49'
[I 160420 12:16:27 server:4380] No SSL private key found.  One will be generated.
Traceback (most recent call last):
  File "/usr/local/bin/gateone", line 9, in <module>
    load_entry_point('gateone==1.2.0', 'console_scripts', 'gateone')()
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/core/server.py", line 4381, in main
    gen_self_signed_ssl(path=ssl_base)
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/core/utils.py", line 408, in gen_self_signed_ssl
    import OpenSSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import rand, crypto, SSL
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/rand.py", line 11, in <module>
    from OpenSSL._util import (
  File "/usr/local/lib/python2.7/dist-packages/OpenSSL/_util.py", line 7, in <module>
    binding = Binding()
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 89, in __init__
    self._ensure_ffi_initialized()
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/openssl/binding.py", line 113, in _ensure_ffi_initialized
    libraries=libraries,
  File "/usr/lib/python2.7/dist-packages/cryptography/hazmat/bindings/utils.py", line 39, in build_ffi
    ffi = cffi.FFI()
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 59, in __init__
    "version mismatch, %s != %s" % (backend.__version__, __version__)
AssertionError: version mismatch, 0.8.6 != 1.5.2

**Comment by extremeshok** [comment]
here you go

````
apt-get remove python-cff -y

pip install --upgrade setuptools

pip install --upgrade cryptography
````
