### ISSUE TITLE
File "/usr/local/bin/gateone", line 5, in <module> ?

### ISSUE THREAD

**Issue by jsjcjsjc** [liftoff/GateOne#647]
Dear sir
I tried to install Gateone via following ssh on a new debian 7 VPS:

apt-get -y update
apt-get install -y python-pip debhelper python-support
pip install tornado

git clone https://github.com/liftoff/GateOne.git
cd GateOne
python ./setup.py install

and chenck the following information
jsjcjsjc@debian:~$ python -V
Python 2.7.3
jsjcjsjc@debian:~$ python -c "import tornado; print(tornado.version)"
4.4.2

But when i run gateone on vps, it still displays error message 
jsjcjsjc@debian:~$ gateone
Traceback (most recent call last):
  File "/usr/local/bin/gateone", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2707, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 686, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 584, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: html5lib>=0.999

Could you please help me on it ?
Thanks a lot

**Comment by sizeoftank** [comment]
try to `pip install html5lib `

**Comment by jsjcjsjc** [comment]
thanks a  lot, problem solved
