### ISSUE TITLE
Can't install using pip3 on Ubuntu

### ISSUE THREAD

**Issue by ysangkok** [liftoff/GateOne#666]
```
janus@janus-ThinkPad-T430:~$ sudo pip3 install gateone
[sudo] password for janus: 
The directory '/home/janus/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/janus/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting gateone
  Downloading gateone-1.2.0.tar.gz (12.0MB)
    100% |████████████████████████████████| 12.0MB 101kB/s 
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/gateone.egg-info
    writing pip-egg-info/gateone.egg-info/PKG-INFO
    writing requirements to pip-egg-info/gateone.egg-info/requires.txt
    writing dependency_links to pip-egg-info/gateone.egg-info/dependency_links.txt
    writing top-level names to pip-egg-info/gateone.egg-info/top_level.txt
    writing entry points to pip-egg-info/gateone.egg-info/entry_points.txt
    writing manifest file 'pip-egg-info/gateone.egg-info/SOURCES.txt'
    file gateone.py (for module gateone) not found
    reading manifest file 'pip-egg-info/gateone.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching '.gitignore'
    warning: no previously-included files matching '*.kate-swp' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pye' found anywhere in distribution
    warning: no previously-included files matching '*.git' found anywhere in distribution
    warning: no previously-included files matching '.directory' found anywhere in distribution
    writing manifest file 'pip-egg-info/gateone.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-nyhe92ce/gateone/setup.py", line 338, in <module>
        files = os.listdir(path)
    FileNotFoundError: [Errno 2] No such file or directory: ''
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-nyhe92ce/gateone/
janus@janus-ThinkPad-T430:~$ 
```

**Comment by ysangkok** [comment]
`sudo pip3 install https://github.com/liftoff/GateOne/archive/master.zip` worked for me...

**Comment by jehutyy** [comment]
I open same issue and closed it right after, it seems that the gateone package in pypi is not the official repository but a fork instead. Thus it install a bugged version ;)

**Comment by ysangkok** [comment]
Closing since I stopped using GateOne.
