### ISSUE TITLE
AttributeError while awaiting

### ISSUE THREAD

**Issue by ysangkok** [liftoff/GateOne#667]
If I write too much data to the terminal from termio, I get 

```
ERROR:root:Encountered error writing to terminal program: [Errno 11] write could not complete without blocking
```

and then the process dies. How can I know if the write will block?

After that error, I get:

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib/python3.5/socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python3.5/socketserver.py", line 681, in __init__
    self.handle()
  File "/usr/lib/python3.5/http/server.py", line 422, in handle
    self.handle_one_request()
  File "/usr/lib/python3.5/http/server.py", line 410, in handle_one_request
    method()
  File "server.py", line 83, in do_GET
    w(str(job.writesome()))
  File "server.py", line 51, in writesome
    self.m.await(1)
  File "/usr/local/lib/python3.5/dist-packages/termio/termio.py", line 1146, in await
    output = self.read() # Remember:  read() is non-blocking
  File "/usr/local/lib/python3.5/dist-packages/termio/termio.py", line 1735, in read
    if remaining_patterns and not self.scheduler._running:
AttributeError: 'MultiplexPOSIXIOLoop' object has no attribute 'scheduler'
```

**Comment by ysangkok** [comment]
Closing since I stopped using GateOne.
