### ISSUE TITLE
first time run of `gateone` give python error

### ISSUE THREAD

**Issue by allenzhao64** [liftoff/GateOne#689]
the installation looks ok. But when `gateone` is issue on command line:

[root@node1 GateOne]# gateone
Traceback (most recent call last):
  File "/usr/bin/gateone", line 9, in <module>
    load_entry_point('gateone==1.2.0', 'console_scripts', 'gateone')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/gateone-1.2.0-py2.7.egg/gateone/core/server.py", line 402, in <module>
    from gateone.auth.authorization import require, authenticated, policies
  File "/usr/lib/python2.7/site-packages/gateone-1.2.0-py2.7.egg/gateone/auth/authorization.py", line 38, in <module>
    @memoize
  File "/usr/lib/python2.7/site-packages/gateone-1.2.0-py2.7.egg/gateone/core/utils.py", line 290, in __init__
    MEMO = AutoExpireDict(timeout=timeout, interval="30s")
  File "/usr/lib/python2.7/site-packages/gateone-1.2.0-py2.7.egg/gateone/core/utils.py", line 161, in __init__
    self.interval = kwargs.pop('interval')
  File "/usr/lib/python2.7/site-packages/gateone-1.2.0-py2.7.egg/gateone/core/utils.py", line 211, in interval
    self._timeout_checker, value, io_loop=self.io_loop)
TypeError: __init__() got an unexpected keyword argument 'io_loop'
Exception AttributeError: "'AutoExpireDict' object has no attribute '_key_watcher'" in <bound method AutoExpireDict.__del__ of {}> ignored
[root@node1 GateOne]#

I am using python 2.7.5 (with the latest CentOS 7)

**Comment by allenzhao64** [comment]
The issue apparently is due to the latest version of tornado used. 

By removing the 5.1a tornado, and do a `pip install tornado==4.5.3`, the gateone starts to function correctly.

**Comment by davama** [comment]
@allenzhao64 this really help! 

I was cracking my head

**Comment by rushi718** [comment]
Yes it really helped thank you

**Comment by Pransu-panwar** [comment]
i am still getting the same error, even after downgrading tornado. please help!

**Comment by shaifali03** [comment]
Upon running the following commands,
graphlab.canvas.set_target('ipynb')
sales.show()

I am getting a long error at the end of which is following-
TypeError: initialize() got an unexpected keyword argument 'io_loop'

Pls share how to rectify this error. Is anybody else doing Coursera's Machine Learning Specialization Course ?
