### ISSUE TITLE
pip install gateone error

### ISSUE THREAD

**Issue by jehutyy** [liftoff/GateOne#695]
Hi everyone, it seems that pip install gateone doesn't work here 

```
root@vm $ pip install gateone                                                                                               ~
Collecting gateone
  Using cached gateone-1.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    running egg_info
    creating pip-egg-info/gateone.egg-info
    writing top-level names to pip-egg-info/gateone.egg-info/top_level.txt
    writing entry points to pip-egg-info/gateone.egg-info/entry_points.txt
    writing dependency_links to pip-egg-info/gateone.egg-info/dependency_links.txt
    writing requirements to pip-egg-info/gateone.egg-info/requires.txt
    writing pip-egg-info/gateone.egg-info/PKG-INFO
    writing manifest file 'pip-egg-info/gateone.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    file gateone.py (for module gateone) not found
    reading manifest file 'pip-egg-info/gateone.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no previously-included files found matching '.gitignore'
    warning: no previously-included files matching '*.kate-swp' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.pye' found anywhere in distribution
    warning: no previously-included files matching '*.git' found anywhere in distribution
    warning: no previously-included files matching '.directory' found anywhere in distribution
    writing manifest file 'pip-egg-info/gateone.egg-info/SOURCES.txt'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-8ath6jf0/gateone/setup.py", line 338, in <module>
        files = os.listdir(path)
    FileNotFoundError: [Errno 2] No such file or directory: ''
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8ath6jf0/gateone/

```

**Comment by jehutyy** [comment]
It seems that pip install gateone refers to this fork https://github.com/jperelli/GateOne/tarball/v1.2.0 and thus doesn't work...
