### ISSUE TITLE
Docker - Ubuntu 16.04 problem

### ISSUE THREAD

**Issue by uketrab** [liftoff/GateOne#701]
Hi,

I have Ubuntu 16.04 fresh installation.
Only executed: apt -y update && apt -y upgrade and then apt -y install docker

root@awfulhak:~# docker run -t --name=gateone -p 443:8000 liftoff/gateone
Unable to find image 'liftoff/gateone:latest' locally
latest: Pulling from liftoff/gateone
660c48dd555d: Pull complete 
4c7380416e78: Pull complete 
421e436b5f80: Pull complete 
e4ce6c3651b3: Pull complete 
be588e74bd34: Pull complete 
958fbfe288f1: Pull complete 
906b78661762: Pull complete 
797187a71ac0: Pull complete 
047fdc0847dd: Pull complete 
43224f4b93cb: Pull complete 
9ca49a42b3c6: Pull complete 
Digest: sha256:4ef7156c3df4d460bb7250ec1fcbba0f6880c0c48926c9aaf6f4be9d2d144d95
Status: Downloaded newer image for liftoff/gateone:latest
Gate One is already up-to-date
Traceback (most recent call last):
  File "/usr/local/bin/gateone", line 9, in <module>
    load_entry_point('gateone==1.2.0', 'console_scripts', 'gateone')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/core/server.py", line 402, in <module>
    from gateone.auth.authorization import require, authenticated, policies
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/auth/authorization.py", line 38, in <module>
    @memoize
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/core/utils.py", line 290, in __init__
    MEMO = AutoExpireDict(timeout=timeout, interval="30s")
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/core/utils.py", line 161, in __init__
    self.interval = kwargs.pop('interval')
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/core/utils.py", line 211, in interval
    self._timeout_checker, value, io_loop=self.io_loop)
TypeError: __init__() got an unexpected keyword argument 'io_loop'
Exception AttributeError: "'AutoExpireDict' object has no attribute '_key_watcher'" in <bound method AutoExpireDict.__del__ of {}> ignored
root@awfulhak:~# 
root@awfulhak:~# cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

root@awfulhak:~# docker -v
Docker version 1.13.1, build 092cba3

root@awfulhak:~# python -V
Python 2.7.12
root@awfulhak:~# 

Does anybody know where can be the problem?

Thank you

**Comment by realbuz** [comment]
+1 on unraid.

**Comment by DrEVILish** [comment]
Same issue here, both on SynologyDSM 6.1.6 & macOS 10.13.4 (17E199) Docker 18.03.0-ce-mac60 (23751)

Traceback (most recent call last):
  File "/usr/local/bin/gateone", line 9, in <module>
    load_entry_point('gateone==1.2.0', 'console_scripts', 'gateone')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/core/server.py", line 402, in <module>
    from gateone.auth.authorization import require, authenticated, policies
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/auth/authorization.py", line 38, in <module>
    @memoize
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/core/utils.py", line 290, in __init__
    MEMO = AutoExpireDict(timeout=timeout, interval="30s")
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/core/utils.py", line 161, in __init__
    self.interval = kwargs.pop('interval')
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/core/utils.py", line 211, in interval
    self._timeout_checker, value, io_loop=self.io_loop)
TypeError: __init__() got an unexpected keyword argument 'io_loop'
Exception AttributeError: "'AutoExpireDict' object has no attribute '_key_watcher'" in <bound method AutoExpireDict.__del__ of {}> ignored

**Comment by GJRTimmer** [comment]
I have the same problem.
Synology 1515+ DSM: latest

**Comment by arush-sal** [comment]
So, for now, I just tried to remove all the instances of the `_key_watcher` and it seems to work. You can find the respective docker image at `arush/gateone`.
Let me know if you someone has a better solution.

**Comment by iamra** [comment]
This issue is both in the Docker image and when building from source for me on Debian.

**Comment by bflorat** [comment]
Same here : 
```
root@vps583249:~# docker run --rm  --name=gateone -t -p 443:8000 liftoff/gateone
Gate One is already up-to-date
Traceback (most recent call last):
  File "/usr/local/bin/gateone", line 9, in <module>
    load_entry_point('gateone==1.2.0', 'console_scripts', 'gateone')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/core/server.py", line 402, in <module>
    from gateone.auth.authorization import require, authenticated, policies
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/auth/authorization.py", line 38, in <module>
    @memoize
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/core/utils.py", line 290, in __init__
    MEMO = AutoExpireDict(timeout=timeout, interval="30s")
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/core/utils.py", line 161, in __init__
    self.interval = kwargs.pop('interval')
  File "/usr/local/lib/python2.7/dist-packages/gateone-1.2.0-py2.7.egg/gateone/core/utils.py", line 211, in interval
    self._timeout_checker, value, io_loop=self.io_loop)
TypeError: __init__() got an unexpected keyword argument 'io_loop'
Exception AttributeError: "'AutoExpireDict' object has no attribute '_key_watcher'" in <bound method AutoExpireDict.__del__ of {}> ignored
root@vps583249:~# docker -v
Docker version 18.06.1-ce, build e68fc7a

```

**Comment by paxinos** [comment]
Thanks!   arush/gateone worked for me as well..   

Is there any chance of the main tree getting fixed?

**Comment by arush-sal** [comment]
@paxinos I don't know/I don't think so. The issue was created like... 10 months ago and yet we haven't had anyone officially from the team respond to it.

**Comment by wendycameron** [comment]
Is there a chance of a pull request fix back to them for fixing the issue.
