### ISSUE TITLE
SSL ERROR TOO WEAK

### ISSUE THREAD

**Issue by arg3t** [liftoff/GateOne#702]
Hello, I recently installed gateone to my system but it wont work. After I run `"python /opt/gateone/gateone.py"` It shows messaged n the termian saying that iy started successfully. However, when I try connecting to "http://localhost:444" It prints this error and the page does not load on the browser.
```

[E 180401 07:07:19 ioloop:334] Exception in I/O handler for fd 5
    Traceback (most recent call last):
      File "/usr/lib/pymodules/python2.7/tornado/ioloop.py", line 327, in start
        self._handlers[fd](fd, events)
      File "/usr/lib/pymodules/python2.7/tornado/netutil.py", line 342, in accept_handler
        callback(connection, address)
      File "/usr/lib/pymodules/python2.7/tornado/netutil.py", line 219, in _handle_connection
        **self.ssl_options)
      File "/usr/lib/python2.7/ssl.py", line 949, in wrap_socket
        ciphers=ciphers)
      File "/usr/lib/python2.7/ssl.py", line 560, in __init__
        self._context.load_cert_chain(certfile, keyfile)
    SSLError: [SSL: CA_MD_TOO_WEAK] ca md too weak (_ssl.c:2771)

```

I dont know the reson for that and I would appreciate any help. 

Thanks in advance

**Comment by yayio** [comment]
You need an https connection,https://localhost:444
