### ISSUE TITLE
SyntaxError: invalid syntax logging.error("Got exception in read: %s" % `e`)

### ISSUE THREAD

**Issue by weituotian** [liftoff/GateOne#708]
```
[root@host gateone]# python --version
Python 3.6.2
[root@host gateone]# python -c "import tornado; print(tornado.version)"
2.4.1
[root@host gateone]# python gateone.py
Traceback (most recent call last):
  File "gateone.py", line 292, in <module>
    import termio, terminal
  File "/opt/gateone/termio.py", line 1596
    logging.error("Got exception in read: %s" % `e`)
                                                ^
SyntaxError: invalid syntax
```

**Comment by PineappleBeer** [comment]
这是因为你用的`python3.6`相对`gateone`来说`版本太高`了，所以出现的`语法错误`，你应该使用`python2.7`来执行`gateone.py`。

**Comment by weituotian** [comment]
@PineappleBeer 哦哦，看看
