### ISSUE TITLE
Error running on Rasbian  stretch

### ISSUE THREAD

**Issue by adigeo** [liftoff/GateOne#711]
pi@murano:~/work/GateOne $ sudo ./run_gateone.py 
[W 180807 14:46:42 locale:61] No translation found for locale: nl_NL
[W 180807 14:46:42 locale:61] No translation found for locale: nl_NL
[W 180807 14:46:42 locale:61] No translation found for locale: nl_NL
Traceback (most recent call last):
  File "./run_gateone.py", line 32, in <module>
    from gateone.core.server import main
  File "/home/pi/work/GateOne/gateone/core/server.py", line 402, in <module>
    from gateone.auth.authorization import require, authenticated, policies
  File "/home/pi/work/GateOne/gateone/auth/authorization.py", line 38, in <module>
    @memoize
  File "/home/pi/work/GateOne/gateone/core/utils.py", line 290, in __init__
    MEMO = AutoExpireDict(timeout=timeout, interval="30s")
  File "/home/pi/work/GateOne/gateone/core/utils.py", line 161, in __init__
    self.interval = kwargs.pop('interval')
  File "/home/pi/work/GateOne/gateone/core/utils.py", line 211, in interval
    self._timeout_checker, value, io_loop=self.io_loop)
TypeError: __init__() got an unexpected keyword argument 'io_loop'
Exception AttributeError: "'AutoExpireDict' object has no attribute '_key_watcher'" in <bound method AutoExpireDict.__del__ of {}> ignored

Looks like an incompatibility with tornado. The setup script installed tornado 5.1

**Comment by GonzRon** [comment]
pip install tornado==4.5
