### ISSUE TITLE
authntication.py TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by lozbrown** [liftoff/GateOne#722]
Suddenly getting this issue with ubuntu 18:04
gateone installed with pip3

> root@gravity:~# /usr/local/bin/gateone
> Traceback (most recent call last):
>   File "/usr/local/bin/gateone", line 11, in <module>
>     load_entry_point('gateone==1.2.0', 'console_scripts', 'gateone')()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 480, in load_entry_point
>     return get_distribution(dist).load_entry_point(group, name)
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2693, in load_entry_point
>     return ep.load()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2324, in load
>     return self.resolve()
>   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2330, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/local/lib/python3.6/dist-packages/gateone/core/server.py", line 398, in <module>
>     from gateone.auth.authentication import NullAuthHandler, KerberosAuthHandler
>   File "/usr/local/lib/python3.6/dist-packages/gateone/auth/authentication.py", line 648
>     next_param = ""
>                   ^
> TabError: inconsistent use of tabs and spaces in indentation
>

**Comment by lozbrown** [comment]
Same applies after installing from a git clone
