### ISSUE TITLE
centos7 import tornado.httpserver  SyntaxError

### ISSUE THREAD

**Issue by fongzii** [liftoff/GateOne#727]
sh-4.2# gateone start
Traceback (most recent call last):
  File "/usr/bin/gateone", line 9, in <module>
    load_entry_point('gateone==1.2.0', 'console_scripts', 'gateone')()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 378, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2566, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2260, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.7/site-packages/gateone-1.2.0-py2.7.egg/gateone/core/server.py", line 361, in <module>
    import tornado.httpserver
  File "/usr/lib64/python2.7/site-packages/tornado/httpserver.py", line 144
    def __init__(self, *args: Any, **kwargs: Any) -> None:
                            ^
SyntaxError: invalid syntax

**Comment by fongzii** [comment]
Upgrade python2.7 to python3.6, tornado.httpserver SyntaxError  was fixed,but gateone code also show SyntaxError  in onoff.py.

**Comment by fongzii** [comment]
The problem was solved, install tornado 4.0,and  close the tornado auto update in 'update_and_run_gateone.py'
