### ISSUE TITLE
gateone.async import issue

### ISSUE THREAD

**Issue by krypterro** [liftoff/GateOne#730]
Ubuntu 16.04 system, with Python3.7

root@admin:/home/krypterro/files/GateOne-master# gateone --help
Traceback (most recent call last):
  File "/usr/local/bin/gateone", line 11, in <module>
    load_entry_point('gateone==1.2.0', 'console_scripts', 'gateone')()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/usr/local/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.7/site-packages/gateone-1.2.0-py3.7.egg/gateone/core/server.py", line 404
    from gateone.async import MultiprocessRunner, ThreadedRunner
                     ^
SyntaxError: invalid syntax
root@admin:/home/krypterro/files/GateOne-master#

**Comment by vincentDcmps** [comment]
same thing on archlinux

**Comment by sylvainpetit** [comment]
same issue on debian 10 - python 3.7.3

**Comment by swimmingchar** [comment]
Python 3.7.0 (default, Sep 14 2018, 15:27:31)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux

That env yet this PB.

**Comment by ghost** [comment]
Ran into the same issue, it would appear that `async` turned into a reserved keyword with py 3.7

**Comment by JoeKun** [comment]
I just opened the following pull request that addresses this issue.

#748: _Stop using reserved keywords `async` and `await`_

**Comment by JoeKun** [comment]
@krypterro Would you mind giving us some context for why you just closed this issue? Is it somehow already resolved?
