### ISSUE TITLE
Gateone gives a 'tornado/httpserver.py' syntax error

### ISSUE THREAD

**Issue by ericxuo** [liftoff/GateOne#735]
Hi,

I did to following to install gateone  : 
$ git clone https://github.com/liftoff/GateOne.git                                                                
$ cd GateOne                                                                                                      
$ python setup.py install

This command ends with  : 

Using /usr/lib/python2.7/site-packages                                                                                          
Finished processing dependencies for gateone==1.2.0                                                                             
Entry points were created for the following:                                                                                    
    console_scripts                                                                                                             
        gateone = gateone.core.server:main                                                                                      
    go_applications                                                                                                             
        example = gateone.applications.example                                                                                  
        terminal = gateone.applications.terminal                                                                                
    go_plugins                                                                                                                  
        editor = gateone.plugins.editor
        help = gateone.plugins.help
    go_terminal_plugins
        bookmarks = gateone.applications.terminal.plugins.bookmarks
        convenience = gateone.applications.terminal.plugins.convenience
        example = gateone.applications.terminal.plugins.example
        html = gateone.applications.terminal.plugins.html
        logging = gateone.applications.terminal.plugins.logging
        notice = gateone.applications.terminal.plugins.notice
        playback = gateone.applications.terminal.plugins.playback
        ssh = gateone.applications.terminal.plugins.ssh                                         

=> Seems OK.

$ which gateone     
/bin/gateone                                                                                              
$ /bin/gateone

This command ends with  : 

Traceback (most recent call last):
  File "/bin/gateone", line 11, in <module>
    load_entry_point('gateone==1.2.0', 'console_scripts', 'gateone')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/gateone-1.2.0-py2.7.egg/gateone/core/server.py", line 361, in <module>
    import tornado.httpserver
  File "/usr/lib/python2.7/site-packages/tornado-6.0.3-py2.7-linux-x86_64.egg/tornado/httpserver.py", line 144
    def __init__(self, *args: Any, **kwargs: Any) -> None:
                            ^
SyntaxError: invalid syntax

Some people [here](https://github.com/arush-sal/cka-practice-environment/issues/8) had the same error but they use docker and I didn't understand how they solved the problem (and my knowledge in docker is really low and I prefer not to use docker).

Can anybody help me ?

Regards.

Xuo.

**Comment by sun51036** [comment]
4.0<tornado<5.0
try tornado==4.1

**Comment by ericxuo** [comment]
Hi,
I'll try on next week-end.

Thank you.

Xuo.

**Comment by ericxuo** [comment]
Hi,

I couldn't install tornado4.1.

# pip2 install tornado-4.2.1-4                                                                    
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.                                            
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip2 install --user` instead.
Collecting tornado-4.2.1-4
  Could not find a version that satisfies the requirement tornado-4.2.1-4 (from versions: )
No matching distribution found for tornado-4.2.1-4

I really need a replacement for gateOne ...

Regards.

Xuo.

**Comment by chickenandpork** [comment]
@ericxuo your command seems like you tried to install tornado==4.2.1 not 4.1 .. that said, both should be available per https://pypi.org/project/tornado/#history .. I would check whether you’re able to download them directly

**Comment by ericxuo** [comment]
Hi,

Thank you for the comment.
I agree I've done something wrong trying to use tornado 4.2 instead of 4.1.
But I think I've removed all the gateone directory, so I'm not sure I'll have time to re-install and try again. I'll see on next week-end.
Currently, I'm using bastillion instead of gateone. It's enough for my needs, even though the copy/paste feature does not work.

Regards.

Xuo.

**Comment by jonpower** [comment]
Im no python expert - but - I got over this by installing tornado 4.1 (I had 3.2.1 previously) .. and I got over that problem ... just to hit the next. Which was a dir creation issue - so - now Im close.

I downloaded tornado 4.1 and just did the standard install.

Got the error below (on Mac OS X)

horribly created /etc/gateone/ssl with 777 permissions .. and .. amazingly ... it seems to be running

talked too soon as soon as a browser connected BANG

Damn - I liked this product

[I 200313 21:39:18 async:514] Shutting down the MultiprocessRunner executor.
[W 200313 21:41:48 iostream:1216] SSL Error on 14 ('127.0.0.1', 55690): [SSL: HTTP_REQUEST] http request (_ssl.c:727)
[W 200313 21:41:48 iostream:1216] SSL Error on 15 ('127.0.0.1', 55691): [SSL: HTTP_REQUEST] http request (_ssl.c:727)
[E 200313 21:41:48 http1connection:700] Uncaught exception




======================================================
[W 200313 21:38:47 app_terminal:2806] dtach command not found.  dtach support has been disabled.
[I 200313 21:38:48 server:4182] Gate One License: AGPLv3 (http://www.gnu.org/licenses/agpl-3.0.html)
[I 200313 21:38:48 server:4191] Imported applications: Terminal
[I 200313 21:38:48 server:4343] Version: 1.2.0 (20171125154235)
[I 200313 21:38:48 server:4344] Tornado version 4.1
[I 200313 21:38:48 server:4364] Connections to this server will be allowed from the following origins: 'localhost:10443 127.0.0.1:10443'
[I 200313 21:38:48 server:4384] No SSL private key found.  One will be generated.
[I 200313 21:38:48 server:3681] No authentication method configured. All users will be ANONYMOUS
[I 200313 21:38:48 server:3762] Loaded global plugins: gateone.plugins.editor, gateone.plugins.help
[I 200313 21:38:48 server:4510] Listening on https://*:10443/
[I 200313 21:38:48 server:4563] Process running with pid 51237
[I 200313 21:39:18 async:514] Shutting down the MultiprocessRunner executor.

======================================================

200313 21:34:56 app_terminal:2806] dtach command not found.  dtach support has been disabled.
[I 200313 21:34:56 server:4182] Gate One License: AGPLv3 (http://www.gnu.org/licenses/agpl-3.0.html)
[I 200313 21:34:56 server:4191] Imported applications: Terminal
[I 200313 21:34:56 server:4343] Version: 1.2.0 (20171125154235)
[I 200313 21:34:56 server:4344] Tornado version 4.1
[I 200313 21:34:56 server:4364] Connections to this server will be allowed from the following origins: 'localhost:10443 127.0.0.1:10443'
[I 200313 21:34:56 server:4384] No SSL private key found.  One will be generated.
Traceback (most recent call last):
  File "/usr/local/bin/gateone", line 11, in <module>
    load_entry_point('gateone==1.2.0', 'console_scripts', 'gateone')()
  File "/Library/Python/2.7/site-packages/gateone-1.2.0-py2.7.egg/gateone/core/server.py", line 4385, in main
    gen_self_signed_ssl(path=ssl_base)
  File "/Library/Python/2.7/site-packages/gateone-1.2.0-py2.7.egg/gateone/core/utils.py", line 414, in gen_self_signed_ssl
    gen_self_signed_func(path=path)
  File "/Library/Python/2.7/site-packages/gateone-1.2.0-py2.7.egg/gateone/core/utils.py", line 533, in gen_self_signed_pyopenssl
    with io.open(keyfile_path, mode='wb') as f:
IOError: [Errno 13] Permission denied: '/etc/gateone/ssl/keyfile.pem'

**Comment by ericxuo** [comment]
Hi,

I can't help. I've been using Bastillion during a few months and now I'm using Apache Guacamole which really works fine.

Regards.

Xuo.
